theme = "modern"
icons = "awesome"

#[[block]]
#block = "net"
#device = "enp0s25"
#ssid = true
#signal_strength = true
#ip = true
#speed_up = false
#graph_up = true
#interval = 5
#use_bits = false
#
#[[block]]
#block = "net"
#device = "wlo1"
#ssid = true
#signal_strength = true
#ip = true
#speed_up = true
#speed_down = true
##graph_up = true
#interval = 5
#use_bits = false
#hide_missing=true


[[block]]
block = "networkmanager"
#on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"


#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "memory"
format_mem = "{Mum}MB({Mup}%)"
format_swap = "{SUm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "memory"
format_mem = "{Mum}MB({Mup}%)"
format_swap = "{SUm}MB({SUp}%)"
display_type = "swap"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "nvidia_gpu"
label = "GT 1060"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "sound"
on_click = "pavucontrol"

#[[block]]
#block = "toggle"
#text = "VGA 1080"
#command_state = "xrandr --listactivemonitors | grep VGA1"
#command_on = "~/.screenlayout/VGA_auto.sh"
#command_off = "~/.screenlayout/default.sh"
#interval = 60


[[block]]
block = "time"
interval = 1
format = "%a %d/%m %X"
